### ISSUE TITLE
Save Error

### ISSUE THREAD

**Issue by YigitDemirag** [songrotek/DQN-Atari-Tensorflow#1]
At timestep 60000, there is a save error.

TIMESTEP 59997 / STATE explore / EPSILON 0.9910027
TIMESTEP 59998 / STATE explore / EPSILON 0.9910018
TIMESTEP 59999 / STATE explore / EPSILON 0.9910009
Traceback (most recent call last):
  File "AtariDQN.py", line 43, in <module>
    main()
  File "AtariDQN.py", line 40, in main
    playAtari()
  File "AtariDQN.py", line 37, in playAtari
    brain.setPerception(nextObservation,action,reward,terminal)
  File "/Users/x0r/Documents/codes/DQN-Atari-Tensorflow/BrainDQN_Nature.py", line 144, in setPerception
    self.trainQNetwork()
  File "/Users/x0r/Documents/codes/DQN-Atari-Tensorflow/BrainDQN_Nature.py", line 131, in trainQNetwork
    self.saver.save(self.session, 'saved_networks/' + 'network' + '-dqn', global_step = self.timeStep)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1037, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
tensorflow.python.framework.errors.NotFoundError: saved_networks/network-dqn-60000.tempstate3373398505739141382
     [[Node: save/save = SaveSlices[T=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/save/tensor_names, save/save/shapes_and_slices, Variable, Variable/RMSProp, Variable/RMSProp_1, Variable_1, Variable_1/RMSProp, Variable_1/RMSProp_1, Variable_10, Variable_11, Variable_12, Variable_13, Variable_14, Variable_15, Variable_16, Variable_17, Variable_18, Variable_19, Variable_2, Variable_2/RMSProp, Variable_2/RMSProp_1, Variable_3, Variable_3/RMSProp, Variable_3/RMSProp_1, Variable_4, Variable_4/RMSProp, Variable_4/RMSProp_1, Variable_5, Variable_5/RMSProp, Variable_5/RMSProp_1, Variable_6, Variable_6/RMSProp, Variable_6/RMSProp_1, Variable_7, Variable_7/RMSProp, Variable_7/RMSProp_1, Variable_8, Variable_8/RMSProp, Variable_8/RMSProp_1, Variable_9, Variable_9/RMSProp, Variable_9/RMSProp_1)]]
Caused by op u'save/save', defined at:
  File "AtariDQN.py", line 43, in <module>
    main()
  File "AtariDQN.py", line 40, in main
    playAtari()
  File "AtariDQN.py", line 20, in playAtari
    brain = BrainDQN(actions)
  File "/Users/x0r/Documents/codes/DQN-Atari-Tensorflow/BrainDQN_Nature.py", line 43, in __init__
    self.saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 832, in **init**
    restore_sequentially=restore_sequentially)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 500, in build
    save_tensor = self._AddSaveOps(filename_tensor, vars_to_save)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 197, in _AddSaveOps
    save = self.save_op(filename_tensor, vars_to_save)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 149, in save_op
    tensor_slices=[vs.slice_spec for vs in vars_to_save])
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/io_ops.py", line 172, in _save
    tensors, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 341, in _save_slices
    name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 661, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()

**Comment by hkhpub** [comment]
I also got exactly the same error.
If somebody knows a workaround, please share.

**Comment by hkhpub** [comment]
I figured out this error is because the directory for saving checkpoint files doesn't exist.
**Simply creating a directory 'saved_networks' solved the problem.**
