### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by Hrhythm** [songrotek/DQN-Atari-Tensorflow#8]
A.L.E: Arcade Learning Environment (version 0.6.0)
[Powered by Stella]
Use -help for help screen.
Warning: couldn't load settings file: ./ale.cfg
Traceback (most recent call last):
  File "AtariDQN.py", line 43, in <module>
    main()
  File "AtariDQN.py", line 40, in main
    playAtari()
  File "AtariDQN.py", line 18, in playAtari
    atari = Atari('breakout.bin')
  File "game/Atari.py", line 9, in __init__
    self.max_frames_per_episode = self.ale.getInt("max_num_frames_per_episode")
  File "/home/hrhythm/anaconda3/lib/python3.6/site-packages/ale_python_interface/ale_python_interface.py", line 122, in getInt
    return ale_lib.getInt(self.obj, key)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
how can i solve this? thank you!

**Comment by thedatamonk** [comment]
> A.L.E: Arcade Learning Environment (version 0.6.0)
> [Powered by Stella]
> Use -help for help screen.
> Warning: couldn't load settings file: ./ale.cfg
> Traceback (most recent call last):
> File "AtariDQN.py", line 43, in 
> main()
> File "AtariDQN.py", line 40, in main
> playAtari()
> File "AtariDQN.py", line 18, in playAtari
> atari = Atari('breakout.bin')
> File "game/Atari.py", line 9, in **init**
> self.max_frames_per_episode = self.ale.getInt("max_num_frames_per_episode")
> File "/home/hrhythm/anaconda3/lib/python3.6/site-packages/ale_python_interface/ale_python_interface.py", line 122, in getInt
> return ale_lib.getInt(self.obj, key)
> ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
> how can i solve this? thank you!

Even I am facing the same issue. On googling about the error, I found a link saying something about adding a rom to the roms directory. But I have no idea where is this roms directory and how to add a rom to it. If you @Hrhythm get any hint from this please let me know.

**Comment by Hrhythm** [comment]
> > A.L.E: Arcade Learning Environment (version 0.6.0)
> > [Powered by Stella]
> > Use -help for help screen.
> > Warning: couldn't load settings file: ./ale.cfg
> > Traceback (most recent call last):
> > File "AtariDQN.py", line 43, in
> > main()
> > File "AtariDQN.py", line 40, in main
> > playAtari()
> > File "AtariDQN.py", line 18, in playAtari
> > atari = Atari('breakout.bin')
> > File "game/Atari.py", line 9, in **init**
> > self.max_frames_per_episode = self.ale.getInt("max_num_frames_per_episode")
> > File "/home/hrhythm/anaconda3/lib/python3.6/site-packages/ale_python_interface/ale_python_interface.py", line 122, in getInt
> > return ale_lib.getInt(self.obj, key)
> > ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
> > how can i solve this? thank you!
> 
> Even I am facing the same issue. On googling about the error, I found a link saying something about adding a rom to the roms directory. But I have no idea where is this roms directory and how to add a rom to it. If you @Hrhythm get any hint from this please let me know.

I didn't solve the promble yet,I choose to use gym as my environment at last.

**Comment by Hrhythm** [comment]
> > A.L.E: Arcade Learning Environment (version 0.6.0)
> > [Powered by Stella]
> > Use -help for help screen.
> > Warning: couldn't load settings file: ./ale.cfg
> > Traceback (most recent call last):
> > File "AtariDQN.py", line 43, in
> > main()
> > File "AtariDQN.py", line 40, in main
> > playAtari()
> > File "AtariDQN.py", line 18, in playAtari
> > atari = Atari('breakout.bin')
> > File "game/Atari.py", line 9, in **init**
> > self.max_frames_per_episode = self.ale.getInt("max_num_frames_per_episode")
> > File "/home/hrhythm/anaconda3/lib/python3.6/site-packages/ale_python_interface/ale_python_interface.py", line 122, in getInt
> > return ale_lib.getInt(self.obj, key)
> > ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
> > how can i solve this? thank you!
> 
> Even I am facing the same issue. On googling about the error, I found a link saying something about adding a rom to the roms directory. But I have no idea where is this roms directory and how to add a rom to it. If you @Hrhythm get any hint from this please let me know.

I didn't solve this problem yet, I choose to use gym as my environment at last.
